# Generated by Django 4.2.7 on 2023-11-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegalEaseHub_app', '0002_rename_member_lawyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('origin', models.CharField(default='Kenya', max_length=50)),
                ('number', models.CharField(default='white', max_length=50)),
            ],
        ),
    ]
