# Generated by Django 4.2.7 on 2023-11-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegalEaseHub_app', '0003_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='number',
            field=models.CharField(default='Civil', max_length=50),
        ),
    ]
